{% set name = "konoha" %}
{% set version = "4.6.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 24a93d27bd428b846dcfacc53bcec9a1b94154062feabf67f3d4ea41c6428c14

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6,<4.0
  run:
    - overrides >=3.0.0,<4.0.0
    - python >=3.6,<4.0

test:
  imports:
    - konoha
    - konoha.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/konoha/
  summary: A tiny sentence/word tokenizer for Japanese text written in Python
  description: |
    Konoha is a Python library for providing easy-to-use integrated interface of
    various Japanese tokenziers, which enables you to switch a tokenizer and
    boost your pre-processing.
  license: MIT
  license_file: LICENSE
  doc_url: https://konoha.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/himkt/konoha

extra:
  recipe-maintainers:
    - BastianZim
